export const alphabet = {
    A: "meow",
    B: "MuR",
    C: "mEow",
    D: "FR",
    E: "MeoW",
    G: "fr",
    H: "MEow",
    I: "Fr",
    J: "mEOW",
    K: "MEOW",
    L: "fR",
    M: "mur",
    O: "meoW",
    Q: "meo",
    R: "meOW",
    T: "mUr",
    U: "Meow",
    V: "Meo",
    W: "muR",
    X: "MEOw",
    Y: "MEO",
    Z: "meOw",
    F: "me",
    N: "Me",
    P: "ME",
    S: "mE",
    // "!": "SHHH",
    
    // А: "meow",
    // Б: "MuR",
    // В: "mEow",
    // Г: "FR",
    // Д: "MeoW",
    // Е: "me",
    // Ё: "fr",
    // Ж: "MEow",
    // З: "Fr",
    // И: "mEOW",
    // Й: "MEOW",
    // К: "fR",
    // Л: "mUr",
    // М: "Me",
    // Н: "meoW",
    // О: "ME",
    // П: "meo",
    // Р: "meOW",
    // С: "mE",
    // Т: "Murr",
    // У: "Meow",
    // Ф: "Meo",
    // Х: "muR",
    // Ц: "MEOw",
    // Ч: "MEO",
    // Ш: "meOw",
    // щ: "mur",
    // Ъ: "MEw",
    // Ы: "mUrr",
    // Ь: "mURr",
    // Э: "MurR",
    // Ю: "mEo",
    // Я: "meOw",
};
